-- AlterTable
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "categoryDetail" TEXT;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "quantity" DOUBLE PRECISION;
ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "unit" TEXT;
